# Generated by Django 3.2.6 on 2021-08-31 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(max_length=250)),
                ('technology', models.CharField(max_length=200)),
            ],
        ),
    ]
