# Generated by Django 3.2.6 on 2021-09-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
