# Generated by Django 3.2.6 on 2021-09-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memento', '0004_education_experience_leadership_referee_relevantcourses_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demo',
            field=models.URLField(default='https://github.com/Barissa-Imran'),
        ),
        migrations.AddField(
            model_name='project',
            name='source_code',
            field=models.URLField(default='https://github.com/Barissa-Imran'),
        ),
        migrations.AlterField(
            model_name='referee',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='core_skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resume',
            name='tech_skills',
            field=models.TextField(),
        ),
    ]
